x86: irq_pipeline: Fix build failure for !IRQ_PIPELINE but X86_FRED
The POSTED_MSI_NOTIFICATION_VECTOR is present since 6.10, so
FIRST_SYSTEM_APIC_VECTOR was off by one resulting in the following build
warning:

./arch/x86/include/asm/irq_vectors.h:104:41: error: array index in initializer exceeds array bounds
  104 | #define POSTED_MSI_NOTIFICATION_VECTOR  0xeb
      |                                         ^~~~
arch/x86/entry/entry_fred.c:98:37: note: in definition of macro ‘SYSVEC’
   98 | #define SYSVEC(_vector, _function) [_vector - FIRST_SYSTEM_VECTOR] = fred_sysvec_##_function
      |                                     ^~~~~~~
arch/x86/entry/entry_fred.c:121:16: note: in expansion of macro ‘POSTED_MSI_NOTIFICATION_VECTOR’
  121 |         SYSVEC(POSTED_MSI_NOTIFICATION_VECTOR,  posted_msi_notification),
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./arch/x86/include/asm/irq_vectors.h:104:41: note: (near initialization for ‘sysvec_table’)
  104 | #define POSTED_MSI_NOTIFICATION_VECTOR  0xeb
      |                                         ^~~~
arch/x86/entry/entry_fred.c:98:37: note: in definition of macro ‘SYSVEC’
   98 | #define SYSVEC(_vector, _function) [_vector - FIRST_SYSTEM_VECTOR] = fred_sysvec_##_function
      |                                     ^~~~~~~
arch/x86/entry/entry_fred.c:121:16: note: in expansion of macro ‘POSTED_MSI_NOTIFICATION_VECTOR’
  121 |         SYSVEC(POSTED_MSI_NOTIFICATION_VECTOR,  posted_msi_notification),
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Required build configuration:
  - CONFIG_IRQ_PIPELINE = n
  - CONFIG_X86_FRED = y

Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>